services:
  postgres:
    container_name: postgres-sql-wac
    image: postgres
    environment:
      POSTGRES_USER: usernamee
      POSTGRES_PASSWORD: passwordd
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: messaging_app
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - messaging-app
    restart: unless-stopped
  keycloak:
    container_name: keycloak-wac
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - messaging-app
    command:
      - "start-dev"
networks:
  messaging-app:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local