/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ChatResponse } from '../models/chat-response';
import { createdChat } from '../fn/chat-controller/created-chat';
import { CreatedChat$Params } from '../fn/chat-controller/created-chat';
import { getChatsByReceiverId } from '../fn/chat-controller/get-chats-by-receiver-id';
import { GetChatsByReceiverId$Params } from '../fn/chat-controller/get-chats-by-receiver-id';
import { StringResponse } from '../models/string-response';

@Injectable({ providedIn: 'root' })
export class ChatControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getChatsByReceiverId()` */
  static readonly GetChatsByReceiverIdPath = '/api/v1';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getChatsByReceiverId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getChatsByReceiverId$Response(params?: GetChatsByReceiverId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ChatResponse>>> {
    return getChatsByReceiverId(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getChatsByReceiverId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getChatsByReceiverId(params?: GetChatsByReceiverId$Params, context?: HttpContext): Observable<Array<ChatResponse>> {
    return this.getChatsByReceiverId$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ChatResponse>>): Array<ChatResponse> => r.body)
    );
  }

  /** Path part for operation `createdChat()` */
  static readonly CreatedChatPath = '/api/v1';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createdChat()` instead.
   *
   * This method doesn't expect any request body.
   */
  createdChat$Response(params: CreatedChat$Params, context?: HttpContext): Observable<StrictHttpResponse<StringResponse>> {
    return createdChat(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createdChat$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  createdChat(params: CreatedChat$Params, context?: HttpContext): Observable<StringResponse> {
    return this.createdChat$Response(params, context).pipe(
      map((r: StrictHttpResponse<StringResponse>): StringResponse => r.body)
    );
  }

}
